apps/bitcoin_crypto/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import *

urlpatterns = [
    url(r'^settings/', SettingsView.as_view(), name='settings'),
    url(r'^exchange-rate/$', ExchangeRateView.as_view(), name='exchange_rate'),
    url(r'^transactions/$', TransactionListView.as_view(), name='transaction_list'),

    #wallets
    url(r'^wallets/$', WalletsView.as_view(), name='wallets'),
    url(r'^sgd-wallets/$', SGDWalletsView.as_view(), name='sgd_wallets'),
    url(r'^update-sgd-wallet/(?P<pk>\d+)/$', AddSGDView.as_view(), name='update_sgd_wallet'),

    url(r'^sendcoin/$', SendTransactionView.as_view(), name='sendcoin'),
    url(r'^sendconfirm/$', SendConfirmView.as_view(), name='sendconfirm'),
    url(r'^confirm-withdrawal/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        SendEmailConfirmView.as_view(), name='confirm_withdrawal'),
    url(r'^pending-transactions/$', PendingTransactionListView.as_view(), name='pending_transactions'),
    url(r'^confirm-pending-transaction/(?P<pk>\d+)/$', ConfirmPendingTransactionView.as_view(), name='confirm_pending_transaction'),
    url(r'^reject-pending-transaction/(?P<pk>\d+)/$', RejectPendingTransactionView.as_view(), name='reject_pending_transaction'),

    url(r'^all-user-wallet-accounts/$', GetAllUserAddresse.as_view(), name='get_all_wallet_users'),
    url(r'^transaction-records/$', TransactionRecordView.as_view(template_name="bitcoin/transaction_record.html"), name='transaction_record'),

    url(r'^set-minimum-limit/$', SetMinimunLimitBTC.as_view(), name='set_minimum_limit'),
    url(r'^wallet-to-vault/$', WalletToVault.as_view(), name='wallet_to_vault'),
    url(r'^confirm-wallet-to-vault/$', ConfirmWalletToVault.as_view(), name='confirm_wallet_to_vault'),
    
    url(r'^vault-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        WalletToVaultEmailConfirm.as_view(), name='vault_confirm'),
    url(r'^vault-transactions/$', VaultTransactionListView.as_view(), name='vault_transaction_list'),
    url(r'^vault-to-wallet/$', VaultToWalletView.as_view(), name='vault_to_wallet'),
    url(r'^vault-list/$', ListVaultView.as_view(), name='vault_list'),

    # order urls
    url(r'^stop-limit-order/$', OrderView.as_view(), name='stop_limit_order'),
    url(r'^depthchart/$', AjaxDepthChartView.as_view(), name='depthchart'),
    url(r'^buy-order-list/$', BuyOrderList.as_view(), name='buy_order_list'),
    url(r'^sell-order-list/$', SellOrderList.as_view(), name='sell_order_list'),
    url(r'^delete-order/(?P<pk>\d+)/$', DeleteOrderView.as_view(), name='delete_order'),

    #notification urls
    url(r'^notifications/$', NotificationListView.as_view(), name='notifications'),

    #report
    url(r'^report/$', DownloadReport.as_view(), name='report'),
    url(r'^ajax-order-book/$', AjaxOrderBookView.as_view(), name='ajax_order_book'),
]

cryptocurrency/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.views.static import serve
from apps.bitcoin_crypto.views import IndexView, WelcomeView
from .utils import ProtectServe


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crypto/', include('apps.bitcoin_crypto.urls', namespace='coins')),
    url(r'^fees/', include('apps.fees.urls', namespace='fees')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^auth/', include('apps.authentication.urls')),
    url(r'^dashboard/', WelcomeView.as_view(), name='welcome'),
    url(r'^exchange/', TemplateView.as_view(template_name='theme/exchange.html'), name='exchange'),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], ProtectServe.as_view(), {'document_root': settings.MEDIA_ROOT})
]

urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/bitcoin_crypto/models.py
from django.db import models
from apps.authentication.models import User
from django.contrib.sites.models import Site
from decimal import Decimal


class WalletAddress(models.Model):
    address = models.CharField(max_length=500, blank=True, default="")

    def __str__(self):
        return self.address


class Wallet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, blank=True, default="")
    addresses = models.ManyToManyField(WalletAddress)
    private = models.CharField(max_length=500, blank=True, default="")
    public = models.CharField(max_length=500, blank=True, default="")
    words = models.CharField(max_length=500, blank=True, default="")

    def __str__(self):
        return self.name + " " + self.user.username


class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.CharField(blank=False, max_length=200)
    balance = models.CharField(blank=True, max_length=20)
    currency = models.CharField(blank=True, max_length=20)
    transaction_id = models.CharField(blank=True, max_length=200)
    transaction_to = models.CharField(blank=True, max_length=200)
    transaction_type = models.CharField(blank=True, max_length=200)
    pending = models.BooleanField(default=True)
    invalid = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)
    transaction_fee = models.CharField(blank=True, max_length=200, default=0)
    mining_fee = models.CharField(blank=True, max_length=200, default=0)
    #last modification of object when transaction confirmed then datetime is auto_now
    date = models.DateTimeField(auto_now=True)

    def transaction_fee_except_mining_fees(self):
        try:
            transaction_fee = Decimal(self.transaction_fee)
        except:
            transaction_fee = 0

        try:
           mining_fee =  Decimal(self.mining_fee)
        except:
            mining_fee = 0

        if transaction_fee > 0:
            transaction_fee = transaction_fee - mining_fee

        return transaction_fee


    def __str__(self):
        return self.user.username


class PendingTransactions(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.CharField(max_length=200)
    currency = models.CharField(max_length=20)
    transaction_to = models.CharField(max_length=200)
    transaction_fee = models.CharField(blank=True, max_length=200)

    def __str__(self):
        return self.user.username


class VaultWallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(blank=False, max_length=200, unique=True)
    name = models.CharField(max_length=20, blank=True, default="")
    addresses = models.ManyToManyField(WalletAddress) 
    private = models.CharField(max_length=500, blank=True, default="")
    public = models.CharField(max_length=500, blank=True, default="")
    words = models.CharField(max_length=500, blank=True, default="")
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username


class VaultTransaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.CharField(blank=False, max_length=200)
    balance = models.CharField(blank=True, max_length=20)
    mining_fee = models.CharField(blank=True, max_length=200, default='0')
    currency = models.CharField(blank=True, max_length=20)
    transaction_id = models.CharField(blank=True, max_length=200)
    transaction_to = models.CharField(blank=True, max_length=200)
    transaction_from = models.CharField(blank=True,default='', max_length=200)
    transaction_type = models.CharField(blank=True, max_length=200, default='to_vault')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class MinimunCoin(models.Model):
    site = models.OneToOneField(Site, on_delete=models.CASCADE)
    btc_limit = models.CharField(max_length=200,default='0.0')
    user_alert = models.BooleanField(default=True)
    low_limit_alert = models.BooleanField(default=True)


class WatchOnlyAddress(models.Model):
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.address


class SGDWallet(models.Model):
    user = models.ForeignKey(User)
    amount = models.FloatField(default=0)

    def __str__(self):
        return self.user.username


class OrderBook(models.Model):
    ORDER_CHOICES = (
        ('0', 'Buy'),
        ('1', 'sell')
    )
    ORDER_MODE = (
        ('0', 'market'),
        ('1', 'limit'),
        ('2', 'stop-limit')
    )

    user = models.ForeignKey(User)
    exchange_form = models.CharField(max_length=5)
    exchange_to = models.CharField(max_length=5)
    amount = models.FloatField()
    price = models.FloatField()
    limit = models.FloatField()
    order_type = models.CharField(choices=ORDER_CHOICES, max_length=2)
    order_mode = models.CharField(choices=ORDER_MODE, max_length=2)
    order_time = models.DateTimeField(auto_now_add=True)
    trade_status = models.BooleanField(default=False)
    coins_covered = models.FloatField(default=0)
    trading_fee = models.FloatField(default=0)
    canceled = models.BooleanField(default=False)
    maker = models.BooleanField(default=False)



    def __str__(self):
        return self.user.username


class OrderMatchingHistory(models.Model):
    processing_order = models.ForeignKey(OrderBook, related_name='processing_order')
    matched_order = models.ForeignKey(OrderBook, related_name='matched_order')
    matching_price = models.FloatField(default=0)
    coins_covered = models.FloatField(default=0)
    trading_fee = models.FloatField(default=0)
    order_matching_time = models.DateTimeField(auto_now_add=True)


class ExchangeTaxRates(models.Model):
    previous_rate = models.FloatField(default=None, null=True, blank=True)
    current_rate = models.FloatField(default=0)
    updated_on = models.DateField(auto_now_add=True, blank=True)
    update_by = models.ForeignKey(User)

    def __str__(self):
        return self.update_by.username



class Notification(models.Model):
    date =  models.DateTimeField(auto_now=True)
    user = models.ManyToManyField(User, through='NotificationUser')
    notification = models.TextField(max_length=128)

    def __str(self):
        return self.notification


class NotificationUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notification = models.ForeignKey(Notification, on_delete=models.CASCADE)
    is_readed = models.BooleanField(default=False)
    is_pending_notification = models.BooleanField(default=False)


class TransactionTracker(models.Model):
    previous_transaction_count = models.CharField(max_length=128)

templates/bitcoin/buy_order_list.html
{% extends 'base.html' %}  
{% load static %}
{% load transaction_status %}

{% block title %}Buy Orders{% endblock %}

{% block content %}
<div class="trans">
  <div class="container">
    <h2 class="Ubuntu mf15">Buy Orders</h2>
    <div class="row m0">
      <div class="col-sm-12">
       <div class="trans-details">
        <div class="tab-content">
            <div class="table-responsive">
              <table class="table table_template darklinks table-striped table-bordered table-hover" id="timetable">
                <thead>
                  <tr>
                   <th>Date</th>
                   <th>Amount</th>
                   <th>Price</th>
                   <th>Trigger</th>
                   <th>Fee</th>
                   <th>Order Mode</th>
                   <th>Filled</th>
                   <th>Trade Status</th>
                   <th>Action</th>
                 </tr>
               </thead>
               <tbody>

                {% for obj in buy_order_list %}
                <tr>
                  <td>{{obj.order_time}}</td>
                  <td>{{ obj.amount }}</td>
                  <td>{{ obj.price }}</td>
                  <td>{% if obj.order_mode == "2" %}{{obj.limit}}{% else %}-{% endif %}</td>
                  <td>{{ obj.trading_fee|floatformat:'3' }}</td>
                  <td>{{ obj.get_order_mode_display }}</td>
                  <td>{% percentage_completed obj.coins_covered obj.amount %}%</td>
                  <td>
                    {% if obj.amount == obj.coins_covered %}
                      Completed
                    {% else %}
                      {{ obj.trade_status|yesno:"Canceled,Pending" }}
                    {% endif %}
                  </td>
                  <td>
                    {% if obj.trade_status == False %}
                      <a href="javascript:void(0)" class="btn btn-danger" onclick="removeOrder('{{obj.pk}}')">Cancel</a>
                     {% endif %}
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="9"> No Buy Orders</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

 <div id="success-modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-body m50 text-center">
                <img class="m30" src="{% static 'img/succes-thumb.png' %}" width="40%">
                <h3 class="Ubuntu">Success</h3>
                &nbsp;
                <h6 class="Ubuntu m0">Order cancelled</h6>
                &nbsp;
            </div>
            <div class="pop-footer" style="text-align: center;">
                <a style="" href="{% url 'coins:buy_order_list' %}" class="btn btn-main">OK</a>
            </div>
        </div>
    </div>
</div>

<div id="error-modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
  <div class="modal-dialog modal-xs">
      <div class="modal-content">
          <div class="modal-body" style="padding: 50px 10px">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <img class="m30" src="{% static 'img/thumb-down.png' %}" width="40%">
              <h4 class="Ubuntu m0">Order can not found.</h4>
          </div>
      </div>
  </div>
</div>

<div id="confirm-modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
  <div class="modal-dialog modal-xs">
      <div class="modal-content">
          <div class="modal-body" style="padding: 50px 10px">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <img class="m30" src="{% static 'img/important.png' %}" width="40%">
              <h4 class="Ubuntu m0">Are you sure to cancel this order ?</h4>
          </div>
          <div class="pop-footer" style="text-align: center;">
                <a style="" href="javascript:void(0)" onclick="confirmRemoval()" class="btn btn-main">yes</a>
            </div>
      </div>
  </div>
</div>

{% endblock content %}

{% block script %}
<script>
  var orderId;
  function removeOrder(pk){
    orderId = pk;
    $('#confirm-modal').modal('show');
  }

  function confirmRemoval(){
    $('#confirm-modal').modal('hide');    
    $.ajax({
      url: "/crypto/delete-order/"+orderId+"/",

      success : function(result){
        if(result.success){
          $('#success-modal').modal('show');
        }else{
          $('#error-modal').modal('show');
        }
      }
    });

  }
</script>
{% endblock %}

{% block footer %}
{% endblock %}

templates/bitcoin/notification_email.html
<h4>Hi {{ user.username }},</h4> </br>
<p><b>{{notification_txt|safe}}</b></p>

<p>Sincerely,</p>
<p>Bullxchange </p>
<p>http://bullxchange.io</p>

templates/bitcoin/notifications.html
{% extends 'base.html' %}  
{% load static %} 

{% block title %}Notifications{% endblock %}

{% block content %}
<div class="trans">
	<div class="container">
		<div class="row m0">
			<div class="col-sm-12">
				<div class="trans-details">
					<div class="tab-content">
						{% if notifications.0 %}
						<div class="table-responsive">
							<table class="table table_template darklinks table-bordered table-hover" id="timetable">
								<thead>
									<tr>
										<th>Date</th>
										<th>Message</th>
									</tr>
								</thead>
								<tbody>

									{% for obj in notifications %}
									<tr {% if forloop.counter <= notification_count %} style="background-color: #f6ebeb" {% endif %}>
										<td>{{obj.date}}</td>
										<td>{{obj.notification|safe}}</td>

									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
						{% else %}
						<p class="text-center"><b> No Notifications</b></p>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

{% block script %}
{% endblock %}

{% block footer %}
{% endblock %}

templates/bitcoin/sell_order_list.html
{% extends 'base.html' %}  
{% load static %}
{% load transaction_status %}

{% block title %}Sell Orders{% endblock %}

{% block content %}
<div class="trans">
  <div class="container">
    <h2 class="Ubuntu mf15">Sell Orders</h2>
    <div class="row m0">
      <div class="col-sm-12">
       <div class="trans-details">
        <div class="tab-content">
            <div class="table-responsive">
              <table class="table table_template darklinks table-striped table-bordered table-hover" id="timetable">
                <thead>
                  <tr>
                   <th>Date &amp; Time</th>
                   <th>Amount</th>
                   <th>Price</th>
                   <th>Trigger</th>
                   <th>Fee</th>
                   <th>Order Mode</th>
                   <th>Filled</th>
                   <th>Trade Status</th>
                   <th>Action</th>
                 </tr>
               </thead>
               <tbody>

                {% for obj in sell_order_list %}
                <tr>
                  <td>{{obj.order_time}}</td>
                  <td>{{ obj.amount }}</td>
                  <td>{{ obj.price }}</td>
                  <td>{% if obj.order_mode == "2" %}{{obj.limit}}{% else %}-{% endif %}</td>
                  <td>{{ obj.trading_fee|floatformat:'3' }}</td>
                  <td>{{ obj.get_order_mode_display }}</td>
                  <td>{% percentage_completed obj.coins_covered obj.amount %}%</td>
                  <td>
                    {% if obj.amount == obj.coins_covered %}
                      Completed
                    {% else %}
                      {{ obj.trade_status|yesno:"Canceled,Pending" }}
                    {% endif %}
                  </td>
                  <td>
                    {% if obj.trade_status == False %}
                      <a href="javascript:void(0)" class="btn btn-danger" onclick="removeOrder('{{obj.pk}}')">Cancel</a>
                    {% endif %}
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="9"> No Sell Orders</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

 <div id="success-modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-body m50 text-center">
                <img class="m30" src="{% static 'img/succes-thumb.png' %}" width="40%">
                <h3 class="Ubuntu">Success</h3>
                &nbsp;
                <h6 class="Ubuntu m0">Order cancelled</h6>
                &nbsp;
            </div>
            <div class="pop-footer" style="text-align: center;">
                <a style="" href="{% url 'coins:sell_order_list' %}" class="btn btn-main">OK</a>
            </div>
        </div>
    </div>
</div>

<div id="error-modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
  <div class="modal-dialog modal-xs">
      <div class="modal-content">
          <div class="modal-body" style="padding: 50px 10px">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <img class="m30" src="{% static 'img/thumb-down.png' %}" width="40%">
              <h4 class="Ubuntu m0">Order can not found.</h4>
          </div>
      </div>
  </div>
</div>

<div id="confirm-modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
  <div class="modal-dialog modal-xs">
      <div class="modal-content">
          <div class="modal-body" style="padding: 50px 10px">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <img class="m30" src="{% static 'img/important.png' %}" width="40%">
              <h4 class="Ubuntu m0">Are you sure to cancel this order ?</h4>
          </div>
          <div class="pop-footer" style="text-align: center;">
                <a style="" href="javascript:void(0)" onclick="confirmRemoval()" class="btn btn-main">yes</a>
            </div>
      </div>
  </div>
</div>

{% endblock content %}

{% block script %}
<script>
  var orderId;
  function removeOrder(pk){
    orderId = pk;
    $('#confirm-modal').modal('show');
  }

  function confirmRemoval(){
    $('#confirm-modal').modal('hide');    
    $.ajax({
      url: "/crypto/delete-order/"+orderId+"/",

      success : function(result){
        if(result.success){
          $('#success-modal').modal('show');
        }else{
          $('#error-modal').modal('show');
        }
      }
    });

  }
</script>
{% endblock %}

{% block footer %}
{% endblock %}

templates/bitcoin/send_to_vault.html
{% extends 'base.html' %} 
{% load static %}
{% load transaction_status %} 

{% block title %}Send to Vault{% endblock title %}

{% block content %}
    <div class="send-coin ">
        <div class="container">
            <h2 class="Ubuntu mb20">Send To Vault</h2>
            <div class="row mb50 send-coin-wrap">
                <div class="row m0">
                    <h4 class="m30"> <b>BTC Main Wallet Details</b> </h4>
                    <div class="row m0 wallet-details">
                        <div class="col-sm-6">
                            <img class="d-inline-block" src="{% static 'img/bitcoin.png' %}" width="40px">
                            <p class="d-inline-block mf10"><b>BTC</b></p>
                        </div>
                        <div class="col-sm-6">
                            <p class="m10 f-medium" align="right">Bal: {% get_account_balance_btc %} BTC</p>
                            <p class="m10 f-medium" align="right"> Current Minimum Limit: {% get_minimum_limit_btc %} BTC</p>
                        </div>
                    </div>
                    <form id="wallettovault" method="post" action="{% url 'coins:wallet_to_vault' %}">
                        {% csrf_token %}
                        <h4 class="m30"><b>Amount to Send</b></h4>
                        <div class="form-group">
                            <input id="amt_2_vault" class="form-control"  placeholder="Enter the Amount to send" name="amount" value="{{form.amount.value}}">
                            <div class="errorlist">{{form.amount.errors|striptags}}</div>
                        </div>

                        <h4 class="m30"><b>Public Address</b></h4>
                        <div class="form-group">
                            <input id="vault_address" class="form-control"  placeholder="Enter Address to Send" name="address" value="{{form.address.value}}">
                            <div class="errorlist">{{form.address.errors|striptags}}</div>
                        </div>

                        <div align="right">
                            <a href="{% url 'welcome' %}" type="button" class="btn-back btn m20 pull-left"> <i class="fas fa-arrow-left"></i> BACK TO DASHBOARD</a>
                            <button type="submit" id="submit_amount" class="btn-main btn m20" >  CONFIRM </button>
                        </div>

                    </from>
                </div>
            </div>
        </div>
    </div>

    <div id="otp-modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-body" style="padding-top: 40px;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="message-text"> Enter SMS OTP</h4>
                <input name="otp"/>
            </div>
            <div class="pop-footer" style="text-align: center;">
                <button type="button" onclick="sendOTP()" class="btn btn-default" style="width: 200px;margin: 0px 11px;">Submit</button>
                <button type="button" onclick="resendOTP()" class="send-otp-btn btn btn-default" style="width: 200px;margin: 0px 11px;">Resend</button>
            </div>
        </div>
    </div>
  </div>

    <div id="success-modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
        <div class="modal-dialog modal-xs">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="modal-body m50 text-center">
                    <img class="m30" src="{% static 'img/important.png' %}" width="40%">
                    <h3 class="Ubuntu">Important</h3>
                    &nbsp;
                    <h4 class="Ubuntu m0 text-center">An email has been send to you. <br>Please click on the link in the email to confirm the withdrawal</h4>
                    &nbsp;
                </div>
                <div class="pop-footer" style="text-align: center;">
                    <a style="" href="{% url 'welcome' %}" class="btn btn-main">OK</a>
                </div>
            </div>
        </div>
    </div>

    <div id="error-modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-body" style="padding: 50px 10px">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <img class="m30" src="{% static 'img/thumb-down.png' %}" width="40%">
                <h4 class="Ubuntu m0"></h4>
            </div>
        </div>
    </div>
  </div>

{% endblock %}

{% block footer %}{% endblock %}

{% block script %}
<script>

    {% if sms_verification %}
        $('#otp-modal').modal('show');
    {% endif %}

    /* code only for testing starts here */
    {% if success %}
        $('#success-modal').modal('show');
    {% endif %}
    /* code only for testing end here */

    function resendOTP(){
        $.ajax({
            type: "POST",
            url: "{% url 'coins:confirm_wallet_to_vault' %}",
            data: {
                'resend-otp': true,
                csrfmiddlewaretoken: '{{ csrf_token }}',
            }
        });
    }

    function sendOTP(){
        var value = $('#otp-modal input').val();
        $.ajax({
            type: "POST",
            url: "{% url 'coins:confirm_wallet_to_vault' %}",
            data: {
                'value': value,
                csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            success: function (data) {
                $("#otp-modal, #error-modal, #success-modal").modal("hide");
                $("#otp-modal .send-otp-btn").hide();
                $('#otp-modal input').val('');

                if(data['success'] == true){
                    $("#success-modal").modal("show");
                }else if(data['status'] == 'otp-not-verified'){
                    $("#otp-modal .message-text").html('Invalid OTP. Try again.')
                    $("#otp-modal .send-otp-btn").show();
                    $("#otp-modal").modal("show");
                }else if(data['status'] == 'get-totp'){
                    $("#otp-modal .message-text").html('Enter Google Authentication Code')
                    $("#otp-modal").modal("show");
                }else if(data['status'] == 'totp-not-verified'){
                    $("#otp-modal .message-text").html('Invalid Google Authentication Code. Try again.')
                    $("#otp-modal").modal("show");
                }else if(data['error']){
                    $("#error-modal .modal-body h4").html(data['error']);
                    $("#error-modal").modal("show");
                }
            }
        });
    }
</script>
{% endblock script %}