apps/fees/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^mining-fees/$', SetMiningFees.as_view(), name='mining_fees'),
    url(r'^set-transaction-fee/$', SetTransactionFee.as_view(), name='set_transaction_fee'),
    url(r'^transaction-fee-list/$', ListTransactionFee.as_view(), name='transaction_fee_list'),
    url(r'^delete-transaction-fee/(?P<pk>\d+)/$', DeleteTransactionFee.as_view(), name='delete_transaction_fee'),
    url(r'^transaction-fee-withdrawal-list/$', TransactionFeeWithdrawalListView.as_view(), name='transaction_fee_withdrawal_list'),

    url(r'^withdraw-fee/$', SendTransactionFeeView.as_view(), name='withdraw_fee'),
    url(r'^withdraw-fee-confirm/$', SendConfirmView.as_view(), name='withdraw-fee-confirm'),
    url(r'^confirm-fee-withdrawal-email/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        SendEmailConfirmView.as_view(), name='confirm_fee_withdrawal_email'),
]

cryptocurrency/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.views.static import serve
from apps.bitcoin_crypto.views import IndexView, WelcomeView
from .utils import ProtectServe


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crypto/', include('apps.bitcoin_crypto.urls', namespace='coins')),
    url(r'^fees/', include('apps.fees.urls', namespace='fees')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^auth/', include('apps.authentication.urls')),
    url(r'^dashboard/', WelcomeView.as_view(), name='welcome'),
    url(r'^exchange/', TemplateView.as_view(template_name='theme/exchange.html'), name='exchange'),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], ProtectServe.as_view(), {'document_root': settings.MEDIA_ROOT})
]

urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/fees/models.py
from django.db import models
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from decimal import Decimal

FEE_TYPE = (
        # ('maker', 'Maker'),
        ('taker', 'Taker'),
        ('withdrawal', 'Withdrawal')
    )

RATE_TYPE = (
        ('fixed', 'Fixed'),
        ('percentage', 'Percentage')
    )

LIMIT = (
        ('greater than or equal to', 'Greater Than or Equal To'),
    )

CURRENCY = (
        ('btc','BTC'),
        ('sgd', 'SGD')
    )

def validate_decimal(value):

    try:
        Decimal(value)
    except:
        raise ValidationError(_('Invalid input'))


class MiningFees(models.Model):
    site = models.OneToOneField(Site, on_delete=models.CASCADE)
    mining_fees = models.CharField(max_length=200,default='0.00', validators=[validate_decimal])


class TransactionFee(models.Model):
    currency = models.CharField(max_length=200, choices=CURRENCY)
    fee_type = models.CharField(max_length=200, choices=FEE_TYPE, unique=True)
    rate_type = models.CharField(max_length=200, choices=RATE_TYPE)


class TransactionFeeRange(models.Model):
    transaction_fee = models.ForeignKey('TransactionFee', on_delete=models.CASCADE)
    limit = models.CharField(max_length=200, choices=LIMIT, default='greater than or equal to')
    value = models.CharField(max_length=200, validators=[validate_decimal])
    fees = models.CharField(max_length=200, validators=[validate_decimal])

    class Meta:
        unique_together = ("transaction_fee", "limit", "value")

    def __str__(self):
        return self.value

apps/fees/forms.py
from django.forms import ModelForm

from .models import TransactionFee


class TransactionFeeForm(ModelForm):
	class Meta:
		model = TransactionFee
		fields = ['fee_type', 'rate_type']

apps/fees/views.py
import json
import pyotp
from decimal import Decimal

from django.shortcuts import render, HttpResponse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import TemplateView
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.contrib.sites.models import Site
from django.views import View
from django.core.mail import send_mail
from django.forms import modelformset_factory
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.conf import settings
from django.utils import six
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.template.loader import render_to_string
from django.urls import reverse
from django.contrib.auth.models import User

from apps.authentication.decorators import check_otp, check_2fa
from apps.authentication.utils import send_otp, _get_pin, send_user_sms, send_admin_sms
from apps.bitcoin_crypto.models import Transaction, PendingTransactions, VaultWallet, MinimunCoin, OrderMatchingHistory
from apps.bitcoin_crypto.utils import *
from .models import *
from .utils import *
from .forms import *



@method_decorator(login_required, name='dispatch')
@method_decorator(check_otp, name='dispatch')
@method_decorator(check_2fa, name='dispatch')
class SetMiningFees(UserPassesTestMixin, TemplateView):
    template_name = 'fees/set_mining_fees.html'

    def test_func(self):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mining_fees_obj, create = MiningFees.objects.get_or_create(site=Site.objects.get_current())

        if create:
            set_mining_fees(Decimal(mining_fees_obj.mining_fees))

        context['mining_fees'] = mining_fees_obj.mining_fees

        return context

    def post(self, request, *args, **kwargs):
        value = request.POST.get('mining_fees')

        try:
            decimal_value = Decimal(value)
        except:
            return HttpResponse(json.dumps({"error": "Invalid Amount."}), content_type='application/json')

        mining_fees_obj, create = MiningFees.objects.get_or_create(site=Site.objects.get_current())

        set_mining_fees(decimal_value)

        mining_fees_obj.mining_fees = value
        mining_fees_obj.save()

        return HttpResponse(json.dumps({"success": True}), content_type='application/json')


@method_decorator(login_required, name='dispatch')
@method_decorator(check_otp, name='dispatch')
@method_decorator(check_2fa, name='dispatch')
class SetTransactionFee(UserPassesTestMixin, View):

    def test_func(self):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return True

    def get(self, request, *args, **kwargs):

        form = TransactionFeeForm()
        TransactionFeeRangeFormSet = modelformset_factory(TransactionFeeRange, fields=('limit', 'value', 'fees'),
            min_num=1, extra=0, validate_min=True)
        formset = TransactionFeeRangeFormSet(prefix='transaction_fee_formset', queryset=TransactionFeeRange.objects.none())
        context = {
            'form' : form,
            'formset': formset
        }

        return render(request, 'fees/set_transaction_fees.html', context)

    def post(self, request, *args, **kwargs):
        form = TransactionFeeForm(request.POST)
        TransactionFeeRangeFormSet = modelformset_factory(TransactionFeeRange, fields=('limit', 'value', 'fees'),
            min_num=1, extra=0, validate_min=True)

        formset = TransactionFeeRangeFormSet(request.POST, prefix='transaction_fee_formset', queryset=TransactionFeeRange.objects.none())

        if form.is_valid() and formset.is_valid():

            transaction_fee_obj = form.save(commit=False)

            if transaction_fee_obj.fee_type == 'taker':
                transaction_fee_obj.currency = 'sgd'
            else:
                transaction_fee_obj.currency = 'btc'

            print(transaction_fee_obj)
            print(transaction_fee_obj.currency)

            transaction_fee_obj.save()

            for form in formset:
                form = form.save(commit=False)
                form.transaction_fee = transaction_fee_obj
                try:
                    form.save()
                except:
                    transaction_fee_obj.delete()
                    status =  'Limit and value pair needs to be unique'
                    return HttpResponse(json.dumps({"status": status}), content_type='application/json')

            status = 'success'
        else:

            status =  'Something Went Wrong'

            for field in form:
                for error in field.errors:
                    status = error

            for error in form.non_field_errors():
                 status = error

            for form in formset:
                for field in form:
                    for error in form.errors:
                        status = error

            for error in formset.non_form_errors():
                status = error

        return HttpResponse(json.dumps({"status": status}), content_type='application/json')


@method_decorator(login_required, name='dispatch')
@method_decorator(check_otp, name='dispatch')
@method_decorator(check_2fa, name='dispatch')
class ListTransactionFee(UserPassesTestMixin, View):

    def test_func(self):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return True

    def get(self, request, *args, **kwargs):
        transaction_fees = TransactionFee.objects.all()
        context = {
            'transaction_fees' : transaction_fees
        }
        return render(request, 'fees/list_transaction_fees.html', context)


@method_decorator(login_required, name='dispatch')
@method_decorator(check_otp, name='dispatch')
@method_decorator(check_2fa, name='dispatch')
class DeleteTransactionFee(UserPassesTestMixin, View):

    def test_func(self):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return True

    def get(self, request, *args, **kwargs):
        try:
            transaction_fee = get_object_or_404(TransactionFee, pk=self.kwargs['pk'])
        except:
            return HttpResponse(json.dumps({"status": 'Object not Found'}), content_type='application/json')

        try:
            transaction_fee.delete()
        except:
            return HttpResponse(json.dumps({"status": 'Object can not delete'}), content_type='application/json')

        return HttpResponse(json.dumps({"status": 'success'}), content_type='application/json')


@method_decorator(login_required, name='dispatch')
@method_decorator(check_otp, name='dispatch')
@method_decorator(check_2fa, name='dispatch')
class TransactionFeeWithdrawalListView(UserPassesTestMixin, View):

    template_name = 'fees/transactions_fee_withdrawal_list.html'

    def test_func(self):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return True

    def get(self, request, *args, **kwargs):
        access = create_connection()
        transactions = access.listtransactions('transaction fee collector')
        send_list = Transaction.objects.filter(transaction_type='fee_withdrawal')
        trade_fee = OrderMatchingHistory.objects.filter(trading_fee__gt=0.0)

        recive_list = [txn for txn in transactions if txn['category'] == 'receive']

        context = {
            'send_list': send_list,
            'recive_list': recive_list,
            'trade_fee': trade_fee
        }
        return render(request, self.template_name, context)


@method_decorator(login_required, name='dispatch')
@method_decorator(check_otp, name='dispatch')
@method_decorator(check_2fa, name='dispatch')
class SendTransactionFeeView(UserPassesTestMixin, TemplateView):
    template_name = 'fees/withdraw_fee.html'

    def test_func(self):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return True

    def post(self, request, *args, **kwargs):
        address = request.POST.get('to')
        request.session['to'] = address

        amount = Decimal(request.POST.get('amount'))
        request.session['amount'] = request.POST.get('amount')

        access = create_connection()
        valid = access.validateaddress(address)
        validate_balance = get_fee_balance()

        if valid['isvalid'] and validate_balance >= amount:
            return HttpResponse(json.dumps({"success":True}), content_type='application/json')
        if valid['isvalid']:
            return HttpResponse(json.dumps({"error":"Insufficient balance"}), content_type='application/json')
        if validate_balance >= amount:
            return HttpResponse(json.dumps({"error":"Please enter a valid address"}), content_type='application/json')
        else:
            return HttpResponse(json.dumps({"error":"Please verify the data"}), content_type='application/json')


class EmailTokenGenerator(PasswordResetTokenGenerator):
    """ Overriding default Password reset token generator for email confirmation"""
    def _make_hash_value(self, user, timestamp):
        return (six.text_type(user.pk) + six.text_type(timestamp)) +  six.text_type(user.is_active)

email_token = EmailTokenGenerator()


@method_decorator(login_required, name='dispatch')
@method_decorator(check_otp, name='dispatch')
@method_decorator(check_2fa, name='dispatch')
class SendConfirmView(UserPassesTestMixin, View):

    def test_func(self):
        if not self.request.user.is_superuser:
            raise PermissionDenied()
        return True

    def post(self, request, *args, **kwargs):
        
        sms_redirect = False

templates/fees/list_transaction_fees.html
{% extends 'base.html' %}  
{% load static %} 
{% load transaction_status %}

{% block title %}Transaction Fees{% endblock %}

{% block extra_styles %}
      <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
{% endblock %}


{% block content %}
<div class="trans">
  <div class="container-fluid">
    <h2 class="Ubuntu mf15 col-sm-8">Transaction Fees</h2>
    <h2 class="col-sm-3"><a href="{% url 'fees:set_transaction_fee' %}" class="btn btn-default">Add Transaction Fees</a></h2>
  </div>
  <div class="row m0">
    <div class="col-sm-12">
      {% for transaction_fee_obj in transaction_fees %}
      <div class="trans-details">
        <div class="tab-content">
          <p><b>Currency</b> : {{ transaction_fee_obj.get_currency_display }}</p>
          <p><b>Fee Type</b> : {{ transaction_fee_obj.get_fee_type_display }}</p>
          <p><b>Rate Type</b> : {{ transaction_fee_obj.get_rate_type_display }}</p>

            <table class="table table-striped table-bordered">
              <tr>
                <th>Limit</th>
                <th>Value</th>
                <th>Fees</th>
              </tr>
              {% for range_obj in transaction_fee_obj.transactionfeerange_set.all %}
                <tr>
                  <td>{{range_obj.get_limit_display}}</td>
                  <td>{{range_obj.value}}</td>
                  <td>{{range_obj.fees}}</td>
                </tr>
              {% endfor %}
            </table>
            <a id="delete-{{forloop.counter}}" href="javascript:void(0)" class="btn btn-default" onclick="confirm({{transaction_fee_obj.pk}})">Delete</a>
      </div>
      </div>
      {% empty %}
      <div class="trans-details">
        <div class="tab-content">
          <h4 align="middle"> Nothing found.</h4>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

<div id="confirm_modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-body">
                <h4>Confirm Delete ?</h4>
            </div>
            <div class="pop-footer" style="text-align: center;">
                <button style="width:150px" type="button" class="btn btn-upload" data-dismiss="modal">Cancel</button>
                <button type="button" onclick="sendConfirm()"  class="btn btn-default" style="width: 200px;margin: 0px 11px;">Confirm</button>
            </div>
        </div>
    </div>
</div>

<div id="success_modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
        <div class="modal-dialog modal-xs">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="modal-body m50 text-center">
                    <img class="m30" src="{% static 'img/succes-thumb.png' %}" width="40%">
                    <h3 class="Ubuntu">Success</h3>
                    &nbsp;
                    <h6 class="Ubuntu m0">Transaction Fee Deleted Successfully</h6>
                    &nbsp;
                </div>
                <div class="pop-footer" style="text-align: center;">
                    <a style="" href="{% url 'fees:transaction_fee_list' %}" class="btn btn-main">OK</a>
                </div>
            </div>
        </div>
    </div>

    <div id="error_modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-body" style="padding: 50px 10px;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <img class="m30" src="{% static 'img/thumb-down.png' %}" width="40%">
                <h4 class="Ubuntu m0">Something went Wrong</h4>
            </div>
        </div>
    </div>
  </div>
{% endblock content %}

{% block footer %}
{% endblock %}

{% block script %}
<script>
  var obj_id;
  function confirm(id){
    obj_id = id;
    $('#confirm_modal').modal("show");
  }

  function sendConfirm(){
    $('#confirm_modal').modal("hide");
    url = "/fees/delete-transaction-fee/" + obj_id;
    $.ajax({
        type: 'GET',
        url: url,
        success: function(result) {
            if(result.status == 'success'){
                $("#success_modal").modal("show");
            }else{
                $("#error_modal .modal-body h4").html('Something went wrong');
                $("#error_modal").modal("show");
            }
        },
        error: function(result) {
            $("#error_modal .modal-body h4").html('Something went wrong');
            $("#error_modal").modal("show");

        }
    });
  }
</script>
{% endblock %}

templates/fees/set_mining_fees.html
{% extends 'base.html' %} 
{% load static %}
{% load transaction_status %} 

{% block title %}Set Mining Fees{% endblock title %}

{% block content %}
    <div class="send-coin ">
        <div class="container">
            <h2 class="Ubuntu mb20">Set Mining Fees</h2>
            <div class="row mb50 send-coin-wrap">
                <div class="row m0">
                    <h4 class="m30"> <b>BTC Mining Fees Details</b></h4>
                    <div class="row m0 wallet-details">
                        <div class="col-sm-6">
                            <img class="d-inline-block" src="{% static 'img/bitcoin.png' %}" width="40px">
                            <p class="d-inline-block mf10"><b>BTC</b></p>
                        </div>
                        <div class="col-sm-6">
                            <p class="m10 f-medium" align="right"> Current Mining Fees: {{mining_fees}} BTC per Kilobyte</p>
                        </div>
                    </div>
                    <div class="">
                        <h4 class="m30"><b>New Mining Fees in BTC per Kilobyte</b></h4>
                        <div class="form-group">
                            <input id="mining_fees" class="form-control"  placeholder="Enter New Mining Fees">
                        </div>

                        <div align="right">
                            <a href="{% url 'welcome' %}" type="button" class="btn-back btn m20 pull-left"> <i class="fas fa-arrow-left"></i> BACK TO DASHBOARD</a>
                            <button type="button" id="submit_amount" class="btn-main btn m20" >  CONFIRM </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="success_modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
        <div class="modal-dialog modal-xs">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="modal-body m50 text-center">
                    <img class="m30" src="{% static 'img/succes-thumb.png' %}" width="40%">
                    <h3 class="Ubuntu">Success</h3>
                    &nbsp;
                    <h6 class="Ubuntu m0">Mining Fees Changed Successfully.</h6>
                    &nbsp;
                </div>
                <div class="pop-footer" style="text-align: center;">
                    <a style="" href="{% url 'welcome' %}" class="btn btn-main">OK</a>
                </div>
            </div>
        </div>
    </div>

    <div id="error_modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-body" style="padding: 50px 10px;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <img class="m30" src="{% static 'img/thumb-down.png' %}" width="40%">
                <h4 class="Ubuntu m0">Please ensure that the input field have value.</h4>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

{% block footer %}{% endblock %}

{% block script %}
<script>
    $('#submit_amount').click(function () {
        mining_fees = $("#mining_fees").val();
        
        if (mining_fees) {
            $.ajax({
                type: 'POST',
                url: "{% url 'fees:mining_fees' %}",
                data: {
                    'mining_fees' : mining_fees,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                success: function(result) {
                    if(result.success){
                        $("#success_modal").modal("show");
                    }else{
                        $("#error_modal .modal-body h4").html(result['error']);
                        $("#error_modal").modal("show");
                    }
                },
                error: function(result) {
                    $("#error_modal .modal-body h4").html('Something went wrong');
                    $("#error_modal").modal("show");

                }
            });
        }
        else {
            $("#error_modal").modal("show")
        }
    });
</script> 
{% endblock script %}

templates/fees/set_transaction_fees.html
{% extends 'base.html' %} 
{% load static %}
{% load transaction_status %}
{% load widget_tweaks %}

{% block title %}Add Transaction Fees{% endblock title %}

{% block content %}
    <div class="send-coin ">
        <div class="container">
            <h2 class="Ubuntu mb20">Add Transaction Fees</h2>
            <div class="row send-coin-wrap">
                <div class="row">
                    <form class="form-horizontal" id="transaction-form">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label class="control-label col-sm-2"><b>{{field.label}} :</b></label>
                                <div class="col-sm-8">
                                    {% render_field field class="form-control" %}
                                </div>
                            </div>
                        {% endfor %}

                        <h4 class="col-sm-offset-1 col-sm-10"><b>Transaction Fees Range</b></h4>

                        {{ formset.management_form }}
                        <div class="col-sm-offset-1 col-sm-10">
                            <table class="table table-striped table-bordered">
                                <thead>
                                  <tr>
                                    <th>Limit</th>
                                    <th>Value</th>
                                    <th>Fees</th>
                                    <th></th>
                                  </tr>
                                </thead>
                                <tbody>
                                    {% for form in formset %}
                                    <tr class="link-formset">
                                        <td>{{ form.id }} {% render_field form.limit class="form-control" %}</td>
                                        <td>{% render_field form.value class="form-control" value="" %}</td>
                                        <td>{% render_field form.fees class="form-control" value="" %}</td>
                                        <td></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="button" id="submit" class="btn-main btn" >  CONFIRM </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div id="success_modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
        <div class="modal-dialog modal-xs">
            <div class="modal-content">
                <div class="modal-body m50 text-center">
                    <img class="m30" src="{% static 'img/succes-thumb.png' %}" width="40%">
                    <h3 class="Ubuntu">Success</h3>
                    &nbsp;
                    <h6 class="Ubuntu m0">Transaction Fee Added Successfully</h6>
                    &nbsp;
                </div>
                <div class="pop-footer" style="text-align: center;">
                    <a style="" href="{% url 'fees:transaction_fee_list' %}" class="btn btn-main">OK</a>
                </div>
            </div>
        </div>
    </div>

    <div id="error_modal" style="background: rgba(11, 11, 11, 0.8);" class="modal bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" data-backdrop="static">
    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-body" style="padding: 50px 10px;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <img class="m30" src="{% static 'img/thumb-down.png' %}" width="40%">
                <h4 class="Ubuntu m0">Please ensure that the input field have value.</h4>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

{% block footer %}{% endblock %}

{% block script %}
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script>
    $('.link-formset').formset({
        prefix: '{{ formset.prefix }}',
        addText: 'add range',
        deleteText: 'remove',
        formCssClass: 'dynamic-formset1'
    });
</script>

<script>
    $('#submit').click(function () {
        not_selected = $("#transaction-form").find('option:checked[value=""]').length;
        $("#transaction-form input[type=text]").each(function(){
             if($(this).val()==""){
                empty_input = true;
             }else{
                empty_input = false;
             }
        });
        if (not_selected == 0 && empty_input == false) {

            $.ajax({
                type: 'POST',
                url: "{% url 'fees:set_transaction_fee' %}",
                data: $("#transaction-form").serialize(),
                success: function(result) {
                    if(result.status=='success'){
                        $("#success_modal").modal("show");
                    }else{
                        console.log(result.status)
                        $("#error_modal .modal-body h4").html(result.status);
                        $("#error_modal").modal("show");
                    }
                },
                error: function(result) {
                    $("#error_modal .modal-body h4").html('Something went wrong');
                    $("#error_modal").modal("show");

                }
            });
        }
        else {
            $("#error_modal .modal-body h4").html('Please ensure that the input field have value');
            $("#error_modal").modal("show")
        }
    });
</script> 
{% endblock script %}